server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-donaciones
              uri: http://localhost:8081
              predicates:
                - Path=/donaciones,/donaciones/**

            - id: ms-logistica
              uri: http://localhost:8082
              predicates:
                - Path=/centros,/centros/**,/envios,/envios/**

            - id: ms-necesidades
              uri: http://localhost:8083
              predicates:
                - Path=/necesidades,/necesidades/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway